version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  telegram-bot:
    build: ./telegram-bot
    container_name: gift_bot
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

