version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "4000:4000"
    environment:
      DB_HOST: 217.114.8.21
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: MyP@ssw0rd!
      DB_NAME: nft
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  telegram-bot:
    build: ./telegram-bot
    container_name: gift_bot
    environment:
      BOT_TOKEN: 8065763008:AAG8WSuwMiKYCArLiJhbkp0JosesLWmHLBs
      API_URL: http://backend:4000  # URL к API, если внутри Docker-сети
    depends_on:
      - backend
    restart: always

